baseURL = 'https://walissonaguirra.dev/'
copyright = "{year}"
languageCode = 'pt-BR'
defaultContentLanguage = 'pt'
theme = 'enchanted-lowkey'
title = 'Walisson Aguirra'
enableRobotsTXT = true
summaryLength = 15
[pagination]
  pagerSize = 5


[services]
  [services.googleAnalytics]
    ID = "G-8KWK0N3QQ6"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = 'dracula'
    tabWidth = 4
