[[main]]
    identifier = "home"
    name = "walissonaguirra.dev"
    url = "/"
    weight = 1

[[main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 2

[[main]]
    identifier = "sobre"
    name = "Sobre"
    url = "/sobre"
    weight = 3

# Social Media Configuration

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/walissonaguirra"
    weight = 1

[[social]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/walissonaguirra"
    weight = 2
